# #####################################################################
# Automatically generated by qmake (2.01a) Mon Jul 28 11:39:15 2008
# #####################################################################
TEMPLATE = app
TARGET = TongueViewer
QT += opengl xml widgets

# Input
HEADERS += glwidget.h \
    ReadSettings.h \
    window.h
SOURCES += glwidget.cpp \
    main.cpp \
    ReadSettings.cpp \
    window.cpp
